# Iso
- fixity: infix 1 <->

# Disj
- fixity: infix 3 <-->

# Conj
- fixity: infix 4 -><-

# Continuation
- fixity: infixl 7 •

# Value
- fixity: infixl 8 ∘

# Seq/Snk/Src
- fixity: infixl 3 ↑
- fixity: infixl 2 ↓

# Control context
- fixity: infixl 1 <==

# Composition
- fixity: infixr 1 •<<
- fixity: infixr 1 >>•
- fixity: infixr 1 ∘<<
- fixity: infixr 1 >>∘

# Env/Res
- fixity: infixl 8 •∘
- fixity: infixl 7 ••


- warn: {name: "Double-negate", lhs: "K (• a)", rhs: "dn a", side: "subst K == K"}
- warn: {name: "Use lmap/compose", lhs: "K ((k •) . f)", rhs: "k <<^ f", side: "subst K == K"}
